# Generated by Django 5.0.14 on 2026-07-06 05:31

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter the title of the blog post.",
                        max_length=255,
                        validators=[blog.models.validate_not_only_whitespace],
                        verbose_name="Title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Enter the body content of the blog post.",
                        validators=[blog.models.validate_not_only_whitespace],
                        verbose_name="Content",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload a cover image for the blog post.",
                        upload_to="blogs/",
                        validators=[blog.models.validate_blog_image],
                        verbose_name="Image",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Python", "Python"),
                            ("Django", "Django"),
                            ("PowerBI", "PowerBI"),
                            ("Scrapy", "Scrapy"),
                        ],
                        help_text="Select a programming or analytics category.",
                        max_length=20,
                        verbose_name="Category",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category"], name="blog_blog_categor_22b357_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="blog_blog_created_e997ae_idx"
                    ),
                ],
            },
        ),
    ]
