# Generated by Django 5.0.14 on 2026-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.BooleanField(default=True, help_text='Check to make the post public.', verbose_name='Publish'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(blank=True, default='', help_text='Enter comma-separated tags.', max_length=255, verbose_name='Tags'),
        ),
    ]
