# Generated by Django 5.0.14 on 2026-07-06 09:39

from django.db import migrations, models

import blog.models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blog_publish_blog_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a cover image for the blog post.",
                null=True,
                upload_to="blogs/",
                validators=[blog.models.validate_blog_image],
                verbose_name="Image",
            ),
        ),
    ]
