# Generated by Django 5.0.14 on 2026-07-07 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Select the author of the blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='blog',
            name='editor',
            field=models.ForeignKey(blank=True, help_text='Select the editor of the blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Editor'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publisher',
            field=models.ForeignKey(blank=True, help_text='Select the publisher of the blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_blogs', to=settings.AUTH_USER_MODEL, verbose_name='Publisher'),
        ),
    ]
